#pragma once

namespace Craftbuild {
	enum class Registry {
		ROOT_REGISTRY_NAME = 0,
		ACTIVITY,
		ATTRIBUTE,
		BIOME_SOURCE,
		BLOCK_ENTITY_TYPE,
		BLOCK_PREDICATE_TYPE,
		BLOCK_STATE_PROVIDER_TYPE,
		BLOCK_TYPE,
		BLOCK,
		CARVER,
		CHUNK_GENERATOR,
		CHUNK_STATUS,
		COMMAND_ARGUMENT_TYPE,
		CONSUME_EFFECT_TYPE,
		CREATIVE_MODE_TAB,
		CUSTOM_STAT,
		DATA_COMPONENT_PREDICATE_TYPE,
		DATA_COMPONENT_TYPE,
		DECORATED_POT_PATTERN,
		DENSITY_FUNCTION_TYPE,
		ENCHANTMENT_EFFECT_COMPONENT_TYPE,
		ENCHANTMENT_ENTITY_EFFECT_TYPE,
		ENCHANTMENT_LEVEL_BASED_VALUE_TYPE,
		ENCHANTMENT_LOCATION_BASED_EFFECT_TYPE,
		ENCHANTMENT_PROVIDER_TYPE,
		ENCHANTMENT_VALUE_EFFECT_TYPE,
		ENTITY_SUB_PREDICATE_TYPE,
		ENTITY_TYPE,
		NOISE
	};
}